### ISSUE TITLE
Blank page When using React Router

### ISSUE THREAD

**Issue by mwalol** [jaredLunde/masonic#5] opened 2020-04-09 14:06 UTC
hi,

Thank you for this library, 

i have a situation where i need to click on an Element on the List  to navigated to another component using react-router-dom.

if i don't use the scroll on the new mounted component then using the back history browser button i get to the ScrollTop postion correctly and the list is well rendred.

but if i use the scroll on the new mounted component and then using the back history, the ScrollTop Position seem to be correct also but the elements are not visible when i check the dom i can see ,

`<div role="griditem" style="width: 448px; z-index: -1000; visibility: hidden; position: absolute; writing-mode: horizontal-tb;">`

if i move the scroll a bit up it become visible again.. is there anyway to fix this?

**Comment by jaredLunde** [comment] 2020-04-09 15:17
Please post a simple reproduction to codesandbox.com and I'll look into it

**Comment by jaredLunde** [comment] 2020-04-09 15:21
I think I know what you're saying but it'd be easier for me to fix any potential bug if I could see the repo :-)

**Comment by mwalol** [comment] 2020-04-09 17:15
here is an example : 

https://codesandbox.io/s/practical-northcutt-the2s?file=/src/components/InfiniteMoviesListV2.js
it doesn't behave the same on codesandbox, the bug occur on a real browser (chrome/firefox..)
on codesandbox the scroll is moved to the top.

**Comment by jaredLunde** [comment] 2020-04-09 20:03
I have some ideas about what might be going on. Will see what I can do my friend.

**Comment by mwalol** [comment] 2020-04-09 21:49
Thank you so much my friend

**Comment by mwalol** [comment] 2020-04-14 13:28
hi Jared,

did you got time to work on this?

**Comment by jaredLunde** [comment] 2020-04-14 15:14
I have not, but if you need a quick fix you could move the window scroll position by 1 pixel down+  up each time the router goes back using `history.listen`

**Comment by mwalol** [comment] 2020-04-14 16:27
that was the workaround i applied but it's buggy in some situation when  the scroller is in the bottom.
thank you anyway, have a good day

**Comment by jaredLunde** [comment] 2020-04-25 15:40
I started working on a refactor with some small breaking changes for v3 and will attempt to address this in the process of that

**Comment by mwalol** [comment] 2020-04-25 20:43
great news Jared, looking forward to try it on my project when it's ready, i will keep an eye on the release v3

**Comment by jaredLunde** [comment] 2020-04-28 02:41
Just released v3 with many fixes and improvements. I'm very interested in knowing whether or not this specific issue was resolved, but no rush!

**Comment by mwalol** [comment] 2020-04-28 15:05
hi Jared,
i can feel a lot of improvement, the loading the more fast but still not accurate when using back browsing ,
Just tried it on the same Demo and it seem that it doesn't return the correct position after few loading more items, i have created a video that show this behavior :

https://www.youtube.com/watch?v=4ZaKXTOLtJQ

if you want me to reupload the demo on codesandbox i can do that

**Comment by jaredLunde** [comment] 2020-04-28 15:37
Are you using the autosizing feature? That is, are you relying on Masonic to determine the size the cells after your images are loaded? I believe I know what's going on here and can assist you in improving that experience.

**Comment by mwalol** [comment] 2020-04-28 16:01
yes i'm relying on the masonic to determine the size using the autosizing.

**Comment by jaredLunde** [comment] 2020-04-28 16:10
Yeah, so what is happening is during the first phase (which does the measurement) the images have not loaded yet and therefore the measurement is slightly off. Before `ResizeObserver` catches the correction, the browser window has already attempted to scroll to the previous section of the page. The problem is that the size of the container is no longer as tall as it was on the previous scroll when everything was measured - so it jumps to the bottom of the page rather than the actual previous scroll position. What I would suggest is (assuming you know the image dimensions ahead of time) deriving the height of the image from the `width` prop provided to your render component. For example:

```jsx harmony
const MyCard = ({width, data: {image: {src, width: imageWidth, height}}) => {
   const imageHeight = (imageWidth / image.width) * height
   return <img src={src} width={width} height={height} />
}
```

In the event that you don't have those dimensions ahead of time, I'd try to provide a better `itemHeightEstimate` to the `<Masonry>` component so that the measurement phase has a better estimation of the expected cell sizes beforehand.

Unfortunately there's really no other way around this due to the multi-phase way masonry layout algorithms work.

**Comment by mwalol** [comment] 2020-04-28 16:36
yes clear, i have tried removing the image and having fixed card height as you can see the new Video Demo

https://www.youtube.com/watch?v=S75ttlP_Fxo

the problem of blank visibility none is back, and also when scrolling to the bottom using the mouse there is no more fetch new items triggred unless you go up few px as show the demo

yes you are right about the height once's i supply the image size it return to the exact position but blank page is again happening

**Comment by jaredLunde** [comment] 2020-04-28 17:01
Alright, I will put a fix out for the blank page issue tonight. Pretty sure I have an idea about what is happening there now. Will also examine what is going on with the infinite loader in this example but my hunch is `onRender` is not being called for some reason.

Thank you for the videos! They've been super helpful.

**Comment by jaredLunde** [comment] 2020-04-29 05:07
Fairly certain I've fixed this as much as is possible within the library itself amidst the fixes released in this latest `3.0.2`

![ezgif-6-1cc53c8b15d3](https://user-images.githubusercontent.com/86995/80561976-8149e680-89a3-11ea-9c33-01fa4cfedee5.gif)

**Comment by mwalol** [comment] 2020-04-29 09:43
i used the v 3.0.2 and seem to produce the same issue

![v3](https://user-images.githubusercontent.com/7727649/80582068-6496c880-8a0e-11ea-9e7f-caab350db481.gif)

can you add the scroll bar on the target page, maybe the issue appear when there is a scroll in the routed page

**Comment by jaredLunde** [comment] 2020-04-29 14:42
There was a scroll bar on both pages in the example I used

**Comment by jaredLunde** [comment] 2020-04-29 14:45
Between reviewing the code numerous times, adding state updates to force phase 1 into phase 2 rendering, testing locally w/ react-router on every major browser, I just find it hard to consider this a library issue at this point. That is, there's not anything in the library that would cause this to occur. My guess in your case is that you need to look into manual [scroll restoration](https://developer.mozilla.org/en-US/docs/Web/API/History/scrollRestoration) or something along those lines.

**Comment by mwalol** [comment] 2020-04-29 14:49
ok Jared,

Thank you for your time and the hard work to bring this amazing library.

i will take time to dig into this issue, please upload a sandboxcode that you used for your example also that i play with it and see exactly on which case this issue is happenning

**Closed** 2020-04-29 14:50 UTC

**Comment by jaredLunde** [comment] 2020-04-29 14:51
Creating a sandbox for you now

**Comment by jaredLunde** [comment] 2020-04-29 14:55
[Here's the code I used in my GIF](https://codesandbox.io/s/masonic-page-transitions-example-1u9kf?file=/src/index.js)

**Comment by mwalol** [comment] 2020-04-29 15:01
got it Thank you
